version: 2.1

orbs:
  sre: tracktor/ci-tools@0.2.2
  gh: circleci/github-cli@2.1.0

references:
  production_context: &production_context
    - docker
    - npm
    - github

executors:
  build-docker:
    docker:
      - image: cimg/node:22.15.1
  publish-npm:
    docker:
      - image: cimg/node:22.15.1
  tests:
    docker:
      - image: cimg/node:22.15.1

jobs:
  run-unit-tests:
    executor: tests
    steps:
      - checkout
      - restore_cache:
          keys:
            - bun-dependencies-{{ checksum "bun.lock" }}
      - run:
          name: Install dependencies
          command: bun install
      - run:
          name: Run unit tests
          command: bun run test
      - save_cache:
          key: bun-dependencies-{{ checksum "bun.lock" }}
          paths:
            - ~/.bun/install/cache
            - node_modules

  chromatic-deployment:
    executor: tests
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - bun-dependencies-{{ checksum "bun.lock" }}
      - run:
          name: Install dependencies
          command: bun install
      - run:
          name: Run Chromatic visual tests
          command: bun run test-visual

  # Docker Build + Publish
  publish-storybook-docker:
    executor: build-docker
    steps:
      - setup_remote_docker:
          version: default
      - checkout
      - sre/load-package-version
      - restore_cache:
          keys:
            - bun-dependencies-{{ checksum "bun.lock" }}
      - run:
          name: Install dependencies
          command: bun install
      - sre/build-docker:
          image_name: "tracktor/design-system-storybook"
          registry_pwd: $CONTAINER_REGISTRY_PWD
          registry_user: $CONTAINER_REGISTRY_USER
          version: $VERSION
          publish: true

  publish-npm:
    executor: publish-npm
    steps:
      - gh/setup
      - checkout
      - restore_cache:
          keys:
            - bun-dependencies-{{ checksum "bun.lock" }}
      - run:
          name: Install dependencies
          command: bun install
      - run:
          name: Create GitHub release
          command: |
            export TAG=$(grep '"version":' ./package.json | cut -d\" -f4)
            gh release create -F CHANGELOG.md $TAG
      - run:
          name: Publish on npm
          command: npm publish --access public


workflows:
  Visual Test:
    when:
      and:
        - not:
            equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - run-unit-tests:
          name: Run unit tests
      - chromatic-deployment:
          name: Chromatic Deployment
  Release:
    when:
      equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - run-unit-tests:
          name: Run unit tests
      - publish-storybook-docker:
          name: Publish Storybook
          context: *production_context
          requires:
            - Run unit tests
      - publish-npm:
          name: Publish NPM
          context: *production_context
          requires:
            - Run unit tests
