version: 2.1

orbs:
  sre: tracktor/ci-tools@0.2.2
  gh: circleci/github-cli@2.1.0

references:
  production_context: &production_context
    - docker
    - npm
    - github

executors:
  build-docker:
    docker:
      - image: cimg/base:current
  publish-npm:
    docker:
      - image: cimg/node:16.17.0

jobs:
  # Docker Build + Publish
  publish-storybook-docker:
    executor: build-docker
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - sre/load-package-version
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - sre/build-docker:
          image_name: "tracktor/design-system-storybook"
          registry_pwd: $CONTAINER_REGISTRY_PWD
          registry_user: $CONTAINER_REGISTRY_USER
          version: $VERSION
          publish: true

  publish-npm:
    executor: publish-npm
    steps:
      - gh/setup
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: Yarn install
          command: yarn
      - run:
          name: Create Github release
          command: |
            export TAG=$(grep '"version":' ./package.json | cut -d\" -f4)
            gh release create -F CHANGELOG.md $TAG
      - run:
          name: publish on npm
          command: yarn publish
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    executor: node/default
    steps:
      - node/restore-workspace
      - run:
          command: yarn test
  chromatic-deployment:
    docker:
      - image: cimg/base:current
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - run: yarn test:visual

workflows:
  chromatic-deploy:
    jobs:
      - chromatic-deployment:
          filters:
            branches:
              only: master
  main:
    when:
      matches:
        pattern: "^master$"
        value: << pipeline.git.branch >>
    jobs:
      - publish-storybook-docker:
          context: *production_context
      - publish-npm:
          context: *production_context
