version: 2.1

orbs:
  sre: tracktor/ci-tools@0.1.5

references:
  production_context: &production_context
    - docker

executors:
  build-docker:
    docker:
      - image: cimg/base:current

jobs:
  # Docker Build + Publish
  publish-storybook-docker:
    executor: build-docker
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - sre/build-docker:
          image_name: "tracktor/design-system-storybook"
          registry_pwd: $CONTAINER_REGISTRY_PWD
          registry_user: $CONTAINER_REGISTRY_USER
          publish: true

workflows:
  main:
    when:
      matches:
        pattern: "^main$"
        value: << pipeline.git.branch >>
    jobs:
      - publish-storybook-docker:
          context: *production_context
